# Generated by Django 3.2.5 on 2021-08-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='reposts',
        ),
    ]
